baseURL = "https://d3adb5.net/"
theme   = "base16"

enableGitInfo = true

markup.tableOfContents.endLevel = 4

markup.goldmark.parser.attribute.block = true
markup.goldmark.parser.attribute.title = true
markup.goldmark.renderer.unsafe = true

defaultContentLanguage = "en"

[params]
  repoUrl = "https://github.com/d3adb5/website"

[languages]
  [languages.en]
    title = "d3adb5's personal website"
    [languages.en.params]
      langName = "English (US)"
      flag = "🇺🇸"
  [languages.pt-br]
    title = "website pessoal de d3adb5"
    [languages.pt-br.params]
      langName = "Português Brasileiro"
      flag = "🇧🇷"
