name: GitHub Pages

on:
  push: { branches: [ main ] }
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - name: Generate static pages
        run: hugo --minify

      - if: success()
        name: Upload built pages
        uses: actions/upload-artifact@v2
        with:
          name: built-site
          path: public

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build ]

    if: success() && github.ref == 'refs/head/master'

    steps:
      - name: Download built pages
        uses: actions/download-artifact@v2
        with: { name: built-site }

      - name: Deploy to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: d3adb5.net
